import { type PlatformConfig, PlatformConfigSchema } from "./config-schema";

const common = {
  limits: {
    titleChars: null,
    bodyChars: null,
    tagsMax: null,
    tagFormat: "none" as const,
    linksMax: null,
    imagesMax: null,
  },
  supports: {
    headings: true,
    codeBlocks: true,
    inlineFormatting: true,
    lists: true,
    quotes: true,
    canonicalUrl: false,
    coverImage: false,
    markdown: false,
  },
  editor: { title: false, subtitle: false, embeds: false, altText: false, notes: [] },
  media: { formats: [], recommendedDimensions: [], maxBytes: null, notes: [] },
  structure: {
    blueprint: ["hook", "context", "evidence", "takeaway"],
    openerStyles: ["claim", "story", "number"],
    closerStyles: ["takeaway", "question"],
    idealWords: [150, 1200] as [number, number],
  },
  headline: {
    medianWords: 9,
    medianChars: 55,
    prefer: ["specific number", "first-hand evidence"],
    avoid: ["all caps", "generic hype"],
    note: "Use measured advice as a tie-breaker, never a promise.",
  },
  voiceDeltas: { formality: 0, technical_depth: 0, directness: 0, claim_strength: 0 },
  promo: {
    policy: "soft" as const,
    ctaAllowed: true,
    ctaPosition: "end" as const,
    selfLinkRatio: null,
    notes: "Lead with useful, specific evidence.",
  },
  lintOverrides: {},
  publish: {
    mode: "export" as const,
    apiNotes: "Draft and export.",
    exportFormats: ["plaintext" as const],
  },
};

function platform(input: PlatformConfig): PlatformConfig {
  return PlatformConfigSchema.parse(input);
}

/**
 * Server-owned defaults for the 11 supported platforms. `null` means the
 * platform does not publish a universal hard limit; it is never an invented cap.
 * Brand-specific writing rules are stored in brand_platform_profile.
 */
export const PLATFORM_CONFIG = [
  platform({
    ...common,
    slug: "medium",
    name: "Medium",
    kind: "longform",
    limits: { ...common.limits, tagsMax: 5, tagFormat: "plain" },
    supports: { ...common.supports, canonicalUrl: true, coverImage: false },
    editor: {
      title: true,
      subtitle: true,
      embeds: true,
      altText: true,
      notes: ["Rich editor; featured image is an inserted image."],
    },
    media: {
      formats: ["jpg", "jpeg", "png", "gif"],
      recommendedDimensions: ["1192px minimum width"],
      maxBytes: 26214400,
      notes: [],
    },
    structure: {
      blueprint: ["hook", "context", "problem", "approach", "results", "takeaway"],
      openerStyles: ["number", "story", "claim"],
      closerStyles: ["takeaway", "cta"],
      idealWords: [1200, 2000],
    },
    voiceDeltas: { ...common.voiceDeltas, formality: 1 },
    promo: { ...common.promo, notes: "One end CTA; use canonical links." },
    publish: {
      mode: "export",
      apiNotes: "Rich-editor export/import.",
      exportFormats: ["html"],
    },
  }),
  platform({
    ...common,
    slug: "devto",
    name: "Dev.to",
    kind: "longform",
    limits: { ...common.limits, tagsMax: 4, tagFormat: "plain" },
    supports: {
      ...common.supports,
      canonicalUrl: true,
      coverImage: true,
      markdown: true,
    },
    editor: {
      title: true,
      subtitle: false,
      embeds: true,
      altText: true,
      notes: ["Markdown, front matter, inline HTML, and Liquid tags."],
    },
    media: {
      formats: ["markdown image", "embed"],
      recommendedDimensions: ["1000ÃƒÆ’Ã¢â‚¬â€420 cover"],
      maxBytes: null,
      notes: [],
    },
    structure: {
      blueprint: ["what_you_will_learn", "setup", "steps", "code", "gotchas", "result"],
      openerStyles: ["number", "claim"],
      closerStyles: ["takeaway", "question"],
      idealWords: [800, 1600],
    },
    voiceDeltas: { ...common.voiceDeltas, technical_depth: 1, claim_strength: -1 },
    promo: { ...common.promo, notes: "Tutorial value first; one end CTA is accepted." },
    publish: { mode: "api", apiNotes: "Forem REST drafts.", exportFormats: ["markdown"] },
  }),
  platform({
    ...common,
    slug: "hashnode",
    name: "Hashnode",
    kind: "longform",
    limits: { ...common.limits, tagFormat: "plain" },
    supports: {
      ...common.supports,
      canonicalUrl: true,
      coverImage: true,
      markdown: true,
    },
    editor: {
      title: true,
      subtitle: true,
      embeds: false,
      altText: true,
      notes: ["Markdown editor with SEO and series controls."],
    },
    media: {
      formats: ["image", "unsplash"],
      recommendedDimensions: ["1200ÃƒÆ’Ã¢â‚¬â€630 cover"],
      maxBytes: null,
      notes: [],
    },
    structure: {
      blueprint: ["hook", "problem", "solution", "code", "results", "takeaway"],
      openerStyles: ["claim", "number"],
      closerStyles: ["takeaway", "cta"],
      idealWords: [900, 1800],
    },
    voiceDeltas: { ...common.voiceDeltas, technical_depth: 1 },
    publish: { mode: "api", apiNotes: "GraphQL API.", exportFormats: ["markdown"] },
  }),
  platform({
    ...common,
    slug: "substack",
    name: "Substack",
    kind: "newsletter",
    limits: { ...common.limits, tagFormat: "plain" },
    supports: { ...common.supports, coverImage: true },
    editor: {
      title: true,
      subtitle: true,
      embeds: true,
      altText: true,
      notes: ["Rich editor with email and web controls."],
    },
    media: {
      formats: ["image", "audio", "video", "embed", "file"],
      recommendedDimensions: [
        "1200ÃƒÆ’Ã¢â‚¬â€630 social preview",
        "1100ÃƒÆ’Ã¢â‚¬â€220 email banner",
      ],
      maxBytes: null,
      notes: ["PDF attachments up to 700 MB; Gmail may clip emails over 102 KB."],
    },
    structure: {
      blueprint: [
        "personal_open",
        "what_happened",
        "argument",
        "what_i_would_do",
        "sign_off",
      ],
      openerStyles: ["story", "observation"],
      closerStyles: ["understatement", "question"],
      idealWords: [900, 1800],
    },
    voiceDeltas: {
      ...common.voiceDeltas,
      formality: -1,
      technical_depth: -1,
      directness: 1,
    },
    promo: {
      ...common.promo,
      policy: "free",
      notes: "Your subscriber list; subscribe CTA is native.",
    },
    publish: {
      mode: "export",
      apiNotes: "No public write API.",
      exportFormats: ["html", "richtext"],
    },
  }),
  platform({
    ...common,
    slug: "reddit",
    name: "Reddit",
    kind: "community",
    limits: {
      ...common.limits,
      titleChars: [0, 300],
      bodyChars: [0, 40000],
      tagsMax: 0,
      imagesMax: null,
    },
    supports: { ...common.supports, markdown: true },
    editor: {
      title: true,
      subtitle: false,
      embeds: false,
      altText: true,
      notes: ["Rich text and desktop Markdown; subreddit rules override defaults."],
    },
    media: {
      formats: ["image", "video", "gallery", "poll", "ama"],
      recommendedDimensions: [],
      maxBytes: null,
      notes: ["Flair, domains, media, and posting frequency are subreddit-controlled."],
    },
    structure: {
      blueprint: ["context", "what_i_did", "numbers", "what_broke", "open_question"],
      openerStyles: ["story", "number", "observation"],
      closerStyles: ["question"],
      idealWords: [300, 900],
    },
    voiceDeltas: {
      ...common.voiceDeltas,
      formality: -2,
      directness: 1,
      claim_strength: -1,
    },
    promo: {
      ...common.promo,
      policy: "banned_in_body",
      ctaAllowed: false,
      ctaPosition: "none",
      selfLinkRatio: 0.1,
      notes: "No CTA or owned-domain link in the body.",
    },
    lintOverrides: { "SL-008": "error", "SL-002": "error", "SL-012": "error" },
    publish: {
      mode: "assisted",
      apiNotes: "Human posts only.",
      exportFormats: ["markdown", "plaintext"],
    },
  }),
  platform({
    ...common,
    slug: "indiehackers",
    name: "Indie Hackers",
    kind: "community",
    limits: { ...common.limits, tagsMax: 0 },
    supports: { ...common.supports, markdown: true },
    editor: {
      title: true,
      subtitle: false,
      embeds: false,
      altText: false,
      notes: ["Markdown subset with externally linked images."],
    },
    media: {
      formats: ["markdown image"],
      recommendedDimensions: [],
      maxBytes: null,
      notes: ["No native cover field."],
    },
    structure: {
      blueprint: ["where_i_am", "number", "what_i_tried", "what_failed", "ask"],
      openerStyles: ["number", "story"],
      closerStyles: ["question"],
      idealWords: [500, 1200],
    },
    voiceDeltas: {
      ...common.voiceDeltas,
      formality: -2,
      technical_depth: -1,
      directness: 1,
      claim_strength: -1,
    },
    promo: {
      ...common.promo,
      policy: "restricted",
      ctaAllowed: false,
      ctaPosition: "none",
      selfLinkRatio: 0.2,
      notes: "Lead with useful insight, not a bare promotion.",
    },
    publish: { mode: "export", apiNotes: "No API.", exportFormats: ["markdown"] },
  }),
  platform({
    ...common,
    slug: "linkedin",
    name: "LinkedIn",
    kind: "microblog",
    limits: { ...common.limits, bodyChars: [0, 3000], tagFormat: "hashtag" },
    supports: { ...common.supports },
    editor: {
      title: false,
      subtitle: false,
      embeds: false,
      altText: true,
      notes: [
        "This config represents posts; articles/newsletter editions have separate article controls.",
      ],
    },
    media: {
      formats: ["image", "video", "document", "link preview"],
      recommendedDimensions: ["1200ÃƒÆ’Ã¢â‚¬â€627 link preview"],
      maxBytes: null,
      notes: [
        "LinkedIn articles support a 2000ÃƒÆ’Ã¢â‚¬â€600 cover and a 125,000-character body separately.",
      ],
    },
    structure: {
      blueprint: ["hook", "context", "specifics", "lesson", "question"],
      openerStyles: ["claim", "number", "story"],
      closerStyles: ["question", "takeaway"],
      idealWords: [120, 300],
    },
    voiceDeltas: { ...common.voiceDeltas, formality: 1, technical_depth: -1 },
    promo: {
      ...common.promo,
      notes: "Use line breaks and native media; put external links in comments.",
    },
    publish: {
      mode: "export",
      apiNotes: "Partner approval required.",
      exportFormats: ["plaintext"],
    },
  }),
  platform({
    ...common,
    slug: "x",
    name: "X",
    kind: "microblog",
    limits: { ...common.limits, bodyChars: [0, 280], tagFormat: "hashtag", imagesMax: 4 },
    supports: { ...common.supports },
    editor: {
      title: false,
      subtitle: false,
      embeds: false,
      altText: true,
      notes: ["Threads connect posts; Premium long posts can reach 25,000 characters."],
    },
    media: {
      formats: ["photo", "gif", "video"],
      recommendedDimensions: [],
      maxBytes: null,
      notes: ["Alt text up to 1,000 characters per image."],
    },
    structure: {
      blueprint: ["hook", "thread_body", "payoff"],
      openerStyles: ["claim", "number"],
      closerStyles: ["none"],
      idealWords: [25, 55],
    },
    voiceDeltas: {
      ...common.voiceDeltas,
      formality: -1,
      technical_depth: 2,
      directness: 1,
    },
    promo: { ...common.promo, notes: "Put links at the end of a thread." },
    publish: {
      mode: "export",
      apiNotes: "Paid API tiers.",
      exportFormats: ["plaintext"],
    },
  }),
  platform({
    ...common,
    slug: "threads",
    name: "Threads",
    kind: "microblog",
    limits: {
      ...common.limits,
      bodyChars: [0, 500],
      tagsMax: 1,
      tagFormat: "plain",
      imagesMax: 10,
    },
    supports: { ...common.supports },
    editor: {
      title: false,
      subtitle: false,
      embeds: false,
      altText: false,
      notes: ["No Markdown; use line breaks, mentions, links, and threads."],
    },
    media: {
      formats: ["image", "video"],
      recommendedDimensions: [
        "1080ÃƒÆ’Ã¢â‚¬â€1440 image",
        "1080ÃƒÆ’Ã¢â‚¬â€1920 vertical video",
      ],
      maxBytes: null,
      notes: ["Videos up to five minutes."],
    },
    structure: {
      blueprint: ["hook", "context", "payoff"],
      openerStyles: ["claim", "story"],
      closerStyles: ["question", "takeaway"],
      idealWords: [50, 110],
    },
    voiceDeltas: { ...common.voiceDeltas, formality: -1, directness: 1 },
    publish: {
      mode: "export",
      apiNotes: "Assisted posting later.",
      exportFormats: ["plaintext"],
    },
  }),
  platform({
    ...common,
    slug: "instagram",
    name: "Instagram",
    kind: "visual",
    limits: {
      ...common.limits,
      bodyChars: [0, 2200],
      tagsMax: 30,
      tagFormat: "hashtag",
      linksMax: 0,
      imagesMax: 20,
    },
    supports: { ...common.supports },
    editor: {
      title: false,
      subtitle: false,
      embeds: false,
      altText: true,
      notes: ["No Markdown; use line breaks, mentions, alt text, and native tags."],
    },
    media: {
      formats: ["jpg", "png", "gif", "mp4", "mov"],
      recommendedDimensions: [
        "1080ÃƒÆ’Ã¢â‚¬â€1350 feed",
        "1080ÃƒÆ’Ã¢â‚¬â€1920 reels/stories",
      ],
      maxBytes: 1073741824,
      notes: ["Native carousels allow up to 20 items; most API tools allow 10."],
    },
    structure: {
      blueprint: ["hook", "caption", "takeaway"],
      openerStyles: ["claim", "story"],
      closerStyles: ["cta", "takeaway"],
      idealWords: [100, 300],
    },
    voiceDeltas: { ...common.voiceDeltas, formality: -1, technical_depth: -1 },
    promo: { ...common.promo, notes: "Caption URLs are not clickable." },
    publish: {
      mode: "assisted",
      apiNotes: "Graph API later.",
      exportFormats: ["plaintext"],
    },
  }),
  platform({
    ...common,
    slug: "newsletter",
    name: "Newsletter",
    kind: "newsletter",
    supports: { ...common.supports },
    editor: {
      title: true,
      subtitle: true,
      embeds: false,
      altText: true,
      notes: ["HTML email with a plain-text alternative; no JavaScript."],
    },
    media: {
      formats: ["jpg", "png", "gif"],
      recommendedDimensions: ["600px email width"],
      maxBytes: null,
      notes: ["Aim for images under 1 MB; use linked thumbnails for video."],
    },
    structure: {
      blueprint: ["personal_open", "argument", "evidence", "sign_off"],
      openerStyles: ["story", "observation"],
      closerStyles: ["cta", "understatement"],
      idealWords: [900, 1800],
    },
    promo: { ...common.promo, policy: "free", notes: "Use descriptive links plus UTMs." },
    publish: {
      mode: "export",
      apiNotes: "Email adapter later.",
      exportFormats: ["html", "richtext"],
    },
  }),
] as const;
